### ISSUE TITLE
Patch cannot be exported and has load dep errors in nightly

### ISSUE THREAD

**Issue by cristianvogel** [cables-gl/cables_docs#965]
poss related to #959  

The patch is using OSC and networking.  It has a couple of dependencies and a few custom ops. 

The error log below, up until `[LoadingStatus]` is on patch load, and after that if I try to export.

The original was created on v0.5.

2 build, and loads ok there, but has the same errors on export.

**Link to simple, reproducible example patch**
I can't export ( due to the problem ) but attach the patch file 

[KymaCommunicationDEV-cables-nightly.cables.zip](https://github.com/user-attachments/files/18572894/KymaCommunicationDEV-cables-nightly.cables.zip)

**Describe the bug**
Should look like this when working in 0.5.2

<img width="977" alt="Image" src="https://github.com/user-attachments/assets/ece86730-b01b-466d-89fd-a45971fadf77" />

**Platform**
Standalone nightly 2025-01-28 
Standalone 0.5.2

**Dev Tools**
```
[electron] failed dependency for Ops.Extension.Standalone.Net.OscSend: Error: ENOTDIR: not a directory, mkdir '/Applications/cables-2025-01-28-nightly.app/Contents/Resources/app.asar/dist/ops/extensions/Ops.Extension.Standalone/Ops.Extension.Standalone.Net.OscSend'undefined
[electron] failed dependency for Ops.Local.Bonjour_v2: TypeError: arg.startsWith is not a functionundefined
[electron] failed dependency for Ops.Local.Osc_v2:
[electron] failed dependency for Ops.Local.OscSend_v2:
[LoadingStatus] finished loading 1 assets in 0.551s
[LoadingStatus] finished loading 1 assets in 0.099s
[errorListener] [ErrorEvent] Cannot read properties of undefined (reading 'send')
Exporter.show	file:///Applications/cables-2025-01-28-nightly.app/Contents/Resources/app.asar/dist/ui/js/cablesui.js@44254:30
[errorListener] PlatformElectron.exportPatch	file:///Applications/cables-2025-01-28-nightly.app/Contents/Resources/app.asar/dist/ui/js/cablesui.js@51384:28
[LogTab] file: "cablesui" line 51383: platform.talkerAPI.send(talkerCommand, { "projectId": projectId }, (err, result) =>
```

**Comment by steam0r** [comment]
try this again in 0.5.5, sorry...

not sure if you are trying to export to html here...be aware that native/npm functionality will not work in html export

**Comment by cristianvogel** [comment]
Actually,  I am trying to build a standalone app! As it seems the only way to do that is to export to html, then export an app from the website? Am I missing a step here?

**Comment by steam0r** [comment]
the osc ops, for example, will not work this way. there is no magic that we can use to make these modules work in the browser (html) and exporting this into an electron exe that is just a player for html will not make them work. we are thinking about adding functionality to the standalone that it can be opened in renderer mode (hide the patchfield) and maybe even fullscreen...then that might work

**Comment by cristianvogel** [comment]
So I can't build a standalone native app in Cables Electron right now if I
use OSC? Is that correct?

**Comment by cristianvogel** [comment]
Thanks for the explanation, I think I understand better the limitations but what about web sockets could I go that route send OSC via web sockets I've done that in plug in dev, between layers with a Cables front end and a C++ back end ...

What I am trying to make is a cross platform stand alone app with a front end in Cables , dealing with data that strictly comes in and out via OSC, and mouse interaction. There's no online element as such.

**Comment by cristianvogel** [comment]
Also, the hidden editor running full screen solution is pretty savvy, and would be fine in my case! 

If the editor works on different hardware, then I can trust the patch would pretty much work seamlessly cross-platform too. As long we we can pipe runtime errors to system logs , so no one ever really knows the patch field is there in the background.

**Comment by steam0r** [comment]
"osc via websocket" is what these ops do: https://dev.cables.gl/ops/Ops.Extension.Osc

this needs a websocket server and then should/would work in the exe export (if that has a connection to the server, that is)

**Comment by cristianvogel** [comment]
Gone down the Tauri / Rust route and hope to wire in the Cables work I already did. Plan to swap out the Cables networking parts and use the Rust backend to do all that.
